apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ikbeneendemoapp-cronjob.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ikbeneendemoapp.cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
{- range .Values.env }
              - name: {{ .name }}
                value: "{{ .value }}"
{- end }
          restartPolicy: OnFailure